// ── Icons.jsx ─────────────────────────────────────────────
// Shared icons using lucide-react
import {
  Bell, User, Home, Users, Calendar, TrendingUp, FileText,
  Settings, Sparkles, Copy, Phone, PhoneCall, ChevronRight,
  ChevronDown, TrendingDown, Minus, LogOut, Star, Search,
  Filter, X, Building2, DollarSign, StickyNote, MessageCircle,
  Send, MessageSquare, PhoneIncoming, Ban, CalendarCheck,
  CheckSquare, Circle, Flag, BarChart2, BarChart3, Handshake,
  Timer, UserCheck, RefreshCw,
} from "lucide-react";

const Icons = {
  bell:          <Bell        size={20} />,
  user:          <User        size={20} />,
  house:         <Home        size={20} />,
  users:         <Users       size={20} />,
  calendar:      <Calendar    size={20} />,
  chart:         <BarChart2   size={20} />,
  task:          <FileText    size={20} />,
  phone:         <Phone       size={13} />,
  phoneCall:     <PhoneCall   size={18} />,
  caretRight:    <ChevronRight size={12} />,
  caretDown:     <ChevronDown  size={14} />,
  trendUp:       <TrendingUp   size={13} />,
  trendDown:     <TrendingDown size={13} />,
  minus:         <Minus        size={13} />,
  signOut:       <LogOut       size={18} />,
  gear:          <Settings     size={18} />,
  sparkle:       <Sparkles     size={18} />,
  copy:          <Copy         size={18} />,
  search:        <Search       size={16} />,
  funnel:        <Filter       size={15} />,
  x:             <X            size={14} />,
  building:      <Building2    size={15} />,
  currency:      <DollarSign   size={15} />,
  note:          <StickyNote   size={15} />,
  whatsapp:      <MessageCircle size={15} />,
  bar:           <BarChart3    size={20} />,
  send:          <Send         size={15} />,
  chat:          <MessageSquare size={13} />,
  callback:      <PhoneIncoming size={13} />,
  prohibit:      <Ban          size={13} />,
  meeting:       <CalendarCheck size={13} />,
  checkSquare:   <CheckSquare  size={16} />,
  circle:        <Circle       size={16} />,
  flag:          <Flag         size={14} />,
  handshake:     <Handshake    size={18} />,
  hourglass:     <Timer        size={18} />,
  calendarCheck: <CalendarCheck size={18} />,
  userCheck:     <UserCheck    size={18} />,
  refreshCw:     <RefreshCw    size={16} />,
};

export default Icons;
